//! The PDF renderer against real producer output (fixtures generated by
//! reportlab, fpdf2 and pikepdf — see `tests/fixtures/README.md`), checked
//! by sampling pixels whose colour the source document fixes, plus a
//! mutation fuzz pass: no truncated or bit-flipped file may panic.

use fbui_doc::pdf::{Document, Error, RenderOptions};
use fbui_doc::tiny_skia::Pixmap;

const INTER: &[u8] = include_bytes!("../../fbui-render/fonts/Inter-Regular.ttf");

fn open(name: &str) -> Document {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    let mut doc = Document::parse(std::fs::read(path).unwrap()).unwrap();
    doc.set_fallback_font(INTER);
    doc
}

fn render(doc: &Document, page: usize) -> Pixmap {
    doc.render_page(page, &RenderOptions::default()).unwrap()
}

/// RGB at a point given in PDF user space (y up), on a zoom-1 render.
fn at(pm: &Pixmap, x: f32, y_up: f32) -> (u8, u8, u8) {
    let p = pm
        .pixel(x as u32, (pm.height() as f32 - y_up) as u32)
        .unwrap()
        .demultiply();
    (p.red(), p.green(), p.blue())
}

/// Dark ("inked") pixels in a band of rows, PDF user space.
fn ink(pm: &Pixmap, y0_up: f32, y1_up: f32) -> usize {
    let h = pm.height() as f32;
    let (r0, r1) = ((h - y1_up) as u32, (h - y0_up) as u32);
    (r0..r1)
        .flat_map(|y| (0..pm.width()).map(move |x| (x, y)))
        .filter(|&(x, y)| {
            let p = pm.pixel(x, y).unwrap();
            (p.red() as u32 + p.green() as u32 + p.blue() as u32) < 300
        })
        .count()
}

#[test]
fn vector_graphics_match_the_source() {
    let doc = open("reportlab.pdf");
    assert_eq!(doc.page_count(), 2);
    assert_eq!(doc.title().as_deref(), Some("fbui-doc fixture"));
    let pm = render(&doc, 0);
    assert_eq!((pm.width(), pm.height()), (400, 300));
    // Header bar #1e3a5f, the red rect, the green circle.
    assert_eq!(at(&pm, 380.0, 290.0), (0x1e, 0x3a, 0x5f));
    assert_eq!(at(&pm, 50.0, 190.0), (255, 0, 0));
    assert_eq!(at(&pm, 240.0, 190.0), (0, 128, 0));
    // The 40%-alpha blue rect over white blends to light blue.
    let (r, g, b) = at(&pm, 200.0, 100.0);
    assert!(
        b == 255 && (140..170).contains(&r) && r == g,
        "alpha blend {r} {g} {b}"
    );
    // Linear gradient clipped to a rect: orange on the left, blue-ish right.
    let (r, _, b) = at(&pm, 25.0, 85.0);
    assert!(r > 200 && b < 80, "gradient start {r} {b}");
    let (r, _, b) = at(&pm, 140.0, 85.0);
    assert!(b > r, "gradient end r{r} b{b}");
    // Radial gradient clipped to a circle: white centre, green rim.
    let c = at(&pm, 270.0, 85.0);
    assert!(c.0 > 220 && c.1 > 220 && c.2 > 220, "radial centre {c:?}");
    let rim = at(&pm, 270.0, 85.0 - 42.0);
    assert!(rim.1 > rim.0 && rim.1 > rim.2, "radial rim {rim:?}");
}

#[test]
fn every_font_kind_draws_text() {
    let doc = open("reportlab.pdf");
    let pm = render(&doc, 1);
    // One line per font kind, 30pt apart from y=270: standard-14 fallback
    // (Helvetica, Times, Courier), embedded TrueType, embedded Type 1.
    for (i, kind) in ["Helvetica", "Times", "Courier", "TrueType", "Type 1"]
        .iter()
        .enumerate()
    {
        let y = 270.0 - 30.0 * i as f32;
        let n = ink(&pm, y - 4.0, y + 12.0);
        assert!(n > 400, "{kind} line has {n} inked pixels");
    }
    // Text render mode 1 (stroke) in red.
    let red = (0..pm.width())
        .flat_map(|x| (240..280).map(move |y| (x, y)))
        .filter(|&(x, y)| {
            let p = pm.pixel(x, y).unwrap().demultiply();
            p.red() > 180 && p.green() < 100
        })
        .count();
    assert!(red > 100, "outlined text: {red} red pixels");
}

#[test]
fn cid_truetype_images_and_soft_masks() {
    let doc = open("fpdf2.pdf");
    let pm = render(&doc, 0);
    // The bold title (Type 0 / CIDFontType2 / Identity-H) is #1e3a5f ink.
    let title = (0..pm.width())
        .flat_map(|x| (30..60).map(move |y| (x, y)))
        .filter(|&(x, y)| {
            let p = pm.pixel(x, y).unwrap().demultiply();
            (p.red(), p.green(), p.blue()) == (0x1e, 0x3a, 0x5f)
        })
        .count();
    assert!(title > 500, "title ink {title}");
    // PNG swatch: blue on its left edge, the yellow disc in its middle.
    let (r, g, b) = (
        pm.pixel(35, 280).unwrap().red(),
        pm.pixel(35, 280).unwrap().green(),
        pm.pixel(35, 280).unwrap().blue(),
    );
    assert!(b > 200 && r < 60, "png left edge {r} {g} {b}");
    let y = pm.pixel(110, 263).unwrap();
    assert!(
        y.red() > 230 && y.green() > 200 && y.blue() < 60,
        "png disc"
    );
    // JPEG swatch (DCTDecode): same picture, same disc.
    let y = pm.pixel(290, 263).unwrap();
    assert!(
        y.red() > 220 && y.green() > 190 && y.blue() < 80,
        "jpeg disc"
    );
    // The alpha PNG (SMask) lets the swatch show through at its corner.
    // Outside the disc the alpha image is fully transparent: the PNG swatch
    // beneath shows unchanged (its green channel is a constant 90; the
    // crimson disc has none).
    let corner = pm.pixel(153, 240).unwrap();
    assert!(
        (80..=100).contains(&corner.green()),
        "smask corner should be transparent: {corner:?}"
    );
}

#[test]
fn xref_streams_and_object_streams() {
    let a = open("fpdf2.pdf");
    let b = open("objstm.pdf");
    assert_eq!(b.page_count(), 2);
    // Same document, different file structure: identical pixels.
    assert_eq!(render(&a, 0).data(), render(&b, 0).data());
    assert_eq!(render(&a, 1).data(), render(&b, 1).data());
}

#[test]
fn a_broken_xref_is_reconstructed() {
    let good = open("reportlab.pdf");
    let bad = open("broken-xref.pdf");
    assert_eq!(bad.page_count(), 2);
    assert_eq!(render(&good, 1).data(), render(&bad, 1).data());
}

#[test]
fn limits_are_errors_not_allocations() {
    let doc = open("fpdf2.pdf");
    let opts = RenderOptions {
        zoom: 50.0,
        max_pixels: 1 << 20,
        ..Default::default()
    };
    assert_eq!(doc.render_page(0, &opts).err(), Some(Error::TooLarge));
    assert_eq!(
        doc.render_page(9, &RenderOptions::default()).err(),
        Some(Error::PageOutOfRange)
    );
    assert!(Document::parse(&b"not a pdf"[..]).is_err());
}

/// xorshift64*, so the fuzz pass is deterministic.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
}

#[test]
fn mutated_files_never_panic() {
    let small = RenderOptions {
        zoom: 0.25,
        ..Default::default()
    };
    let mut rng = Rng(0x5eed);
    for name in ["reportlab.pdf", "fpdf2.pdf", "objstm.pdf"] {
        let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
        let orig = std::fs::read(path).unwrap();
        for round in 0..60 {
            let mut data = orig.clone();
            if round % 3 == 0 {
                // Truncate somewhere.
                let cut = (rng.next() as usize) % data.len();
                data.truncate(cut.max(16));
            } else {
                // Flip a burst of bytes.
                for _ in 0..(1 + rng.next() % 40) {
                    let i = (rng.next() as usize) % data.len();
                    data[i] = rng.next() as u8;
                }
            }
            if let Ok(mut doc) = Document::parse(data) {
                doc.set_fallback_font(INTER);
                for p in 0..doc.page_count().min(3) {
                    let _ = doc.render_page(p, &small);
                }
            }
        }
    }
}
