//! Simple-font encodings (ISO 32000-1 Annex D) and glyph-name → Unicode
//! for the names those encodings use (a subset of the Adobe Glyph List),
//! plus the `uniXXXX`/`uXXXX` conventions. Generated tables; do not edit by
//! hand.

pub type Encoding = [Option<&'static [u8]>; 256];

#[rustfmt::skip]
pub static STANDARD: Encoding = [
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    Some(b"space"), Some(b"exclam"), Some(b"quotedbl"), Some(b"numbersign"), Some(b"dollar"), Some(b"percent"), Some(b"ampersand"), Some(b"quoteright"),
    Some(b"parenleft"), Some(b"parenright"), Some(b"asterisk"), Some(b"plus"), Some(b"comma"), Some(b"hyphen"), Some(b"period"), Some(b"slash"),
    Some(b"zero"), Some(b"one"), Some(b"two"), Some(b"three"), Some(b"four"), Some(b"five"), Some(b"six"), Some(b"seven"),
    Some(b"eight"), Some(b"nine"), Some(b"colon"), Some(b"semicolon"), Some(b"less"), Some(b"equal"), Some(b"greater"), Some(b"question"),
    Some(b"at"), Some(b"A"), Some(b"B"), Some(b"C"), Some(b"D"), Some(b"E"), Some(b"F"), Some(b"G"),
    Some(b"H"), Some(b"I"), Some(b"J"), Some(b"K"), Some(b"L"), Some(b"M"), Some(b"N"), Some(b"O"),
    Some(b"P"), Some(b"Q"), Some(b"R"), Some(b"S"), Some(b"T"), Some(b"U"), Some(b"V"), Some(b"W"),
    Some(b"X"), Some(b"Y"), Some(b"Z"), Some(b"bracketleft"), Some(b"backslash"), Some(b"bracketright"), Some(b"asciicircum"), Some(b"underscore"),
    Some(b"quoteleft"), Some(b"a"), Some(b"b"), Some(b"c"), Some(b"d"), Some(b"e"), Some(b"f"), Some(b"g"),
    Some(b"h"), Some(b"i"), Some(b"j"), Some(b"k"), Some(b"l"), Some(b"m"), Some(b"n"), Some(b"o"),
    Some(b"p"), Some(b"q"), Some(b"r"), Some(b"s"), Some(b"t"), Some(b"u"), Some(b"v"), Some(b"w"),
    Some(b"x"), Some(b"y"), Some(b"z"), Some(b"braceleft"), Some(b"bar"), Some(b"braceright"), Some(b"asciitilde"), None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, Some(b"exclamdown"), Some(b"cent"), Some(b"sterling"), Some(b"fraction"), Some(b"yen"), Some(b"florin"), Some(b"section"),
    Some(b"currency"), Some(b"quotesingle"), Some(b"quotedblleft"), Some(b"guillemotleft"), Some(b"guilsinglleft"), Some(b"guilsinglright"), Some(b"fi"), Some(b"fl"),
    None, Some(b"endash"), Some(b"dagger"), Some(b"daggerdbl"), Some(b"periodcentered"), None, Some(b"paragraph"), Some(b"bullet"),
    Some(b"quotesinglbase"), Some(b"quotedblbase"), Some(b"quotedblright"), Some(b"guillemotright"), Some(b"ellipsis"), Some(b"perthousand"), None, Some(b"questiondown"),
    None, Some(b"grave"), Some(b"acute"), Some(b"circumflex"), Some(b"tilde"), Some(b"macron"), Some(b"breve"), Some(b"dotaccent"),
    Some(b"dieresis"), None, Some(b"ring"), Some(b"cedilla"), None, Some(b"hungarumlaut"), Some(b"ogonek"), Some(b"caron"),
    Some(b"emdash"), None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, Some(b"AE"), None, Some(b"ordfeminine"), None, None, None, None,
    Some(b"Lslash"), Some(b"Oslash"), Some(b"OE"), Some(b"ordmasculine"), None, None, None, None,
    None, Some(b"ae"), None, None, None, Some(b"dotlessi"), None, None,
    Some(b"lslash"), Some(b"oslash"), Some(b"oe"), Some(b"germandbls"), None, None, None, None,
];

#[rustfmt::skip]
pub static WIN_ANSI: Encoding = [
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    Some(b"space"), Some(b"exclam"), Some(b"quotedbl"), Some(b"numbersign"), Some(b"dollar"), Some(b"percent"), Some(b"ampersand"), Some(b"quotesingle"),
    Some(b"parenleft"), Some(b"parenright"), Some(b"asterisk"), Some(b"plus"), Some(b"comma"), Some(b"hyphen"), Some(b"period"), Some(b"slash"),
    Some(b"zero"), Some(b"one"), Some(b"two"), Some(b"three"), Some(b"four"), Some(b"five"), Some(b"six"), Some(b"seven"),
    Some(b"eight"), Some(b"nine"), Some(b"colon"), Some(b"semicolon"), Some(b"less"), Some(b"equal"), Some(b"greater"), Some(b"question"),
    Some(b"at"), Some(b"A"), Some(b"B"), Some(b"C"), Some(b"D"), Some(b"E"), Some(b"F"), Some(b"G"),
    Some(b"H"), Some(b"I"), Some(b"J"), Some(b"K"), Some(b"L"), Some(b"M"), Some(b"N"), Some(b"O"),
    Some(b"P"), Some(b"Q"), Some(b"R"), Some(b"S"), Some(b"T"), Some(b"U"), Some(b"V"), Some(b"W"),
    Some(b"X"), Some(b"Y"), Some(b"Z"), Some(b"bracketleft"), Some(b"backslash"), Some(b"bracketright"), Some(b"asciicircum"), Some(b"underscore"),
    Some(b"grave"), Some(b"a"), Some(b"b"), Some(b"c"), Some(b"d"), Some(b"e"), Some(b"f"), Some(b"g"),
    Some(b"h"), Some(b"i"), Some(b"j"), Some(b"k"), Some(b"l"), Some(b"m"), Some(b"n"), Some(b"o"),
    Some(b"p"), Some(b"q"), Some(b"r"), Some(b"s"), Some(b"t"), Some(b"u"), Some(b"v"), Some(b"w"),
    Some(b"x"), Some(b"y"), Some(b"z"), Some(b"braceleft"), Some(b"bar"), Some(b"braceright"), Some(b"asciitilde"), None,
    Some(b"Euro"), None, Some(b"quotesinglbase"), Some(b"florin"), Some(b"quotedblbase"), Some(b"ellipsis"), Some(b"dagger"), Some(b"daggerdbl"),
    Some(b"circumflex"), Some(b"perthousand"), Some(b"Scaron"), Some(b"guilsinglleft"), Some(b"OE"), None, Some(b"Zcaron"), None,
    None, Some(b"quoteleft"), Some(b"quoteright"), Some(b"quotedblleft"), Some(b"quotedblright"), Some(b"bullet"), Some(b"endash"), Some(b"emdash"),
    Some(b"tilde"), Some(b"trademark"), Some(b"scaron"), Some(b"guilsinglright"), Some(b"oe"), None, Some(b"zcaron"), Some(b"Ydieresis"),
    Some(b"space"), Some(b"exclamdown"), Some(b"cent"), Some(b"sterling"), Some(b"currency"), Some(b"yen"), Some(b"brokenbar"), Some(b"section"),
    Some(b"dieresis"), Some(b"copyright"), Some(b"ordfeminine"), Some(b"guillemotleft"), Some(b"logicalnot"), Some(b"hyphen"), Some(b"registered"), Some(b"macron"),
    Some(b"degree"), Some(b"plusminus"), Some(b"twosuperior"), Some(b"threesuperior"), Some(b"acute"), Some(b"mu"), Some(b"paragraph"), Some(b"periodcentered"),
    Some(b"cedilla"), Some(b"onesuperior"), Some(b"ordmasculine"), Some(b"guillemotright"), Some(b"onequarter"), Some(b"onehalf"), Some(b"threequarters"), Some(b"questiondown"),
    Some(b"Agrave"), Some(b"Aacute"), Some(b"Acircumflex"), Some(b"Atilde"), Some(b"Adieresis"), Some(b"Aring"), Some(b"AE"), Some(b"Ccedilla"),
    Some(b"Egrave"), Some(b"Eacute"), Some(b"Ecircumflex"), Some(b"Edieresis"), Some(b"Igrave"), Some(b"Iacute"), Some(b"Icircumflex"), Some(b"Idieresis"),
    Some(b"Eth"), Some(b"Ntilde"), Some(b"Ograve"), Some(b"Oacute"), Some(b"Ocircumflex"), Some(b"Otilde"), Some(b"Odieresis"), Some(b"multiply"),
    Some(b"Oslash"), Some(b"Ugrave"), Some(b"Uacute"), Some(b"Ucircumflex"), Some(b"Udieresis"), Some(b"Yacute"), Some(b"Thorn"), Some(b"germandbls"),
    Some(b"agrave"), Some(b"aacute"), Some(b"acircumflex"), Some(b"atilde"), Some(b"adieresis"), Some(b"aring"), Some(b"ae"), Some(b"ccedilla"),
    Some(b"egrave"), Some(b"eacute"), Some(b"ecircumflex"), Some(b"edieresis"), Some(b"igrave"), Some(b"iacute"), Some(b"icircumflex"), Some(b"idieresis"),
    Some(b"eth"), Some(b"ntilde"), Some(b"ograve"), Some(b"oacute"), Some(b"ocircumflex"), Some(b"otilde"), Some(b"odieresis"), Some(b"divide"),
    Some(b"oslash"), Some(b"ugrave"), Some(b"uacute"), Some(b"ucircumflex"), Some(b"udieresis"), Some(b"yacute"), Some(b"thorn"), Some(b"ydieresis"),
];

#[rustfmt::skip]
pub static MAC_ROMAN: Encoding = [
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    None, None, None, None, None, None, None, None,
    Some(b"space"), Some(b"exclam"), Some(b"quotedbl"), Some(b"numbersign"), Some(b"dollar"), Some(b"percent"), Some(b"ampersand"), Some(b"quotesingle"),
    Some(b"parenleft"), Some(b"parenright"), Some(b"asterisk"), Some(b"plus"), Some(b"comma"), Some(b"hyphen"), Some(b"period"), Some(b"slash"),
    Some(b"zero"), Some(b"one"), Some(b"two"), Some(b"three"), Some(b"four"), Some(b"five"), Some(b"six"), Some(b"seven"),
    Some(b"eight"), Some(b"nine"), Some(b"colon"), Some(b"semicolon"), Some(b"less"), Some(b"equal"), Some(b"greater"), Some(b"question"),
    Some(b"at"), Some(b"A"), Some(b"B"), Some(b"C"), Some(b"D"), Some(b"E"), Some(b"F"), Some(b"G"),
    Some(b"H"), Some(b"I"), Some(b"J"), Some(b"K"), Some(b"L"), Some(b"M"), Some(b"N"), Some(b"O"),
    Some(b"P"), Some(b"Q"), Some(b"R"), Some(b"S"), Some(b"T"), Some(b"U"), Some(b"V"), Some(b"W"),
    Some(b"X"), Some(b"Y"), Some(b"Z"), Some(b"bracketleft"), Some(b"backslash"), Some(b"bracketright"), Some(b"asciicircum"), Some(b"underscore"),
    Some(b"grave"), Some(b"a"), Some(b"b"), Some(b"c"), Some(b"d"), Some(b"e"), Some(b"f"), Some(b"g"),
    Some(b"h"), Some(b"i"), Some(b"j"), Some(b"k"), Some(b"l"), Some(b"m"), Some(b"n"), Some(b"o"),
    Some(b"p"), Some(b"q"), Some(b"r"), Some(b"s"), Some(b"t"), Some(b"u"), Some(b"v"), Some(b"w"),
    Some(b"x"), Some(b"y"), Some(b"z"), Some(b"braceleft"), Some(b"bar"), Some(b"braceright"), Some(b"asciitilde"), None,
    Some(b"Adieresis"), Some(b"Aring"), Some(b"Ccedilla"), Some(b"Eacute"), Some(b"Ntilde"), Some(b"Odieresis"), Some(b"Udieresis"), Some(b"aacute"),
    Some(b"agrave"), Some(b"acircumflex"), Some(b"adieresis"), Some(b"atilde"), Some(b"aring"), Some(b"ccedilla"), Some(b"eacute"), Some(b"egrave"),
    Some(b"ecircumflex"), Some(b"edieresis"), Some(b"iacute"), Some(b"igrave"), Some(b"icircumflex"), Some(b"idieresis"), Some(b"ntilde"), Some(b"oacute"),
    Some(b"ograve"), Some(b"ocircumflex"), Some(b"odieresis"), Some(b"otilde"), Some(b"uacute"), Some(b"ugrave"), Some(b"ucircumflex"), Some(b"udieresis"),
    Some(b"dagger"), Some(b"degree"), Some(b"cent"), Some(b"sterling"), Some(b"section"), Some(b"bullet"), Some(b"paragraph"), Some(b"germandbls"),
    Some(b"registered"), Some(b"copyright"), Some(b"trademark"), Some(b"acute"), Some(b"dieresis"), Some(b"notequal"), Some(b"AE"), Some(b"Oslash"),
    Some(b"infinity"), Some(b"plusminus"), Some(b"lessequal"), Some(b"greaterequal"), Some(b"yen"), Some(b"mu"), Some(b"partialdiff"), Some(b"summation"),
    Some(b"product"), Some(b"pi"), Some(b"integral"), Some(b"ordfeminine"), Some(b"ordmasculine"), Some(b"Omega"), Some(b"ae"), Some(b"oslash"),
    Some(b"questiondown"), Some(b"exclamdown"), Some(b"logicalnot"), Some(b"radical"), Some(b"florin"), Some(b"approxequal"), Some(b"Delta"), Some(b"guillemotleft"),
    Some(b"guillemotright"), Some(b"ellipsis"), Some(b"space"), Some(b"Agrave"), Some(b"Atilde"), Some(b"Otilde"), Some(b"OE"), Some(b"oe"),
    Some(b"endash"), Some(b"emdash"), Some(b"quotedblleft"), Some(b"quotedblright"), Some(b"quoteleft"), Some(b"quoteright"), Some(b"divide"), Some(b"lozenge"),
    Some(b"ydieresis"), Some(b"Ydieresis"), Some(b"fraction"), Some(b"Euro"), Some(b"guilsinglleft"), Some(b"guilsinglright"), Some(b"fi"), Some(b"fl"),
    Some(b"daggerdbl"), Some(b"periodcentered"), Some(b"quotesinglbase"), Some(b"quotedblbase"), Some(b"perthousand"), Some(b"Acircumflex"), Some(b"Ecircumflex"), Some(b"Aacute"),
    Some(b"Edieresis"), Some(b"Egrave"), Some(b"Iacute"), Some(b"Icircumflex"), Some(b"Idieresis"), Some(b"Igrave"), Some(b"Oacute"), Some(b"Ocircumflex"),
    Some(b"apple"), Some(b"Ograve"), Some(b"Uacute"), Some(b"Ucircumflex"), Some(b"Ugrave"), Some(b"dotlessi"), Some(b"circumflex"), Some(b"tilde"),
    Some(b"macron"), Some(b"breve"), Some(b"dotaccent"), Some(b"ring"), Some(b"cedilla"), Some(b"hungarumlaut"), Some(b"ogonek"), Some(b"caron"),
];

/// `(glyph name, code point)`, sorted by name for binary search.
#[rustfmt::skip]
static NAME_TO_UNICODE: &[(&[u8], u32)] = &[
    (b"A", 0x0041),
    (b"AE", 0x00C6),
    (b"Aacute", 0x00C1),
    (b"Acircumflex", 0x00C2),
    (b"Adieresis", 0x00C4),
    (b"Agrave", 0x00C0),
    (b"Aring", 0x00C5),
    (b"Atilde", 0x00C3),
    (b"B", 0x0042),
    (b"C", 0x0043),
    (b"Ccedilla", 0x00C7),
    (b"D", 0x0044),
    (b"Delta", 0x2206),
    (b"E", 0x0045),
    (b"Eacute", 0x00C9),
    (b"Ecircumflex", 0x00CA),
    (b"Edieresis", 0x00CB),
    (b"Egrave", 0x00C8),
    (b"Eth", 0x00D0),
    (b"Euro", 0x20AC),
    (b"F", 0x0046),
    (b"G", 0x0047),
    (b"Gamma", 0x0393),
    (b"H", 0x0048),
    (b"I", 0x0049),
    (b"Iacute", 0x00CD),
    (b"Icircumflex", 0x00CE),
    (b"Idieresis", 0x00CF),
    (b"Igrave", 0x00CC),
    (b"J", 0x004A),
    (b"K", 0x004B),
    (b"L", 0x004C),
    (b"Lambda", 0x039B),
    (b"Lslash", 0x0141),
    (b"M", 0x004D),
    (b"N", 0x004E),
    (b"Ntilde", 0x00D1),
    (b"O", 0x004F),
    (b"OE", 0x0152),
    (b"Oacute", 0x00D3),
    (b"Ocircumflex", 0x00D4),
    (b"Odieresis", 0x00D6),
    (b"Ograve", 0x00D2),
    (b"Omega", 0x2126),
    (b"Oslash", 0x00D8),
    (b"Otilde", 0x00D5),
    (b"P", 0x0050),
    (b"Phi", 0x03A6),
    (b"Pi", 0x03A0),
    (b"Psi", 0x03A8),
    (b"Q", 0x0051),
    (b"R", 0x0052),
    (b"S", 0x0053),
    (b"Scaron", 0x0160),
    (b"Sigma", 0x03A3),
    (b"T", 0x0054),
    (b"Theta", 0x0398),
    (b"Thorn", 0x00DE),
    (b"U", 0x0055),
    (b"Uacute", 0x00DA),
    (b"Ucircumflex", 0x00DB),
    (b"Udieresis", 0x00DC),
    (b"Ugrave", 0x00D9),
    (b"V", 0x0056),
    (b"W", 0x0057),
    (b"X", 0x0058),
    (b"Xi", 0x039E),
    (b"Y", 0x0059),
    (b"Yacute", 0x00DD),
    (b"Ydieresis", 0x0178),
    (b"Z", 0x005A),
    (b"Zcaron", 0x017D),
    (b"a", 0x0061),
    (b"aacute", 0x00E1),
    (b"acircumflex", 0x00E2),
    (b"acute", 0x00B4),
    (b"adieresis", 0x00E4),
    (b"ae", 0x00E6),
    (b"agrave", 0x00E0),
    (b"alpha", 0x03B1),
    (b"ampersand", 0x0026),
    (b"apple", 0xF8FF),
    (b"approxequal", 0x2248),
    (b"aring", 0x00E5),
    (b"arrowdown", 0x2193),
    (b"arrowleft", 0x2190),
    (b"arrowright", 0x2192),
    (b"arrowup", 0x2191),
    (b"asciicircum", 0x005E),
    (b"asciitilde", 0x007E),
    (b"asterisk", 0x002A),
    (b"at", 0x0040),
    (b"atilde", 0x00E3),
    (b"b", 0x0062),
    (b"backslash", 0x005C),
    (b"bar", 0x007C),
    (b"beta", 0x03B2),
    (b"braceleft", 0x007B),
    (b"braceright", 0x007D),
    (b"bracketleft", 0x005B),
    (b"bracketright", 0x005D),
    (b"breve", 0x02D8),
    (b"brokenbar", 0x00A6),
    (b"bullet", 0x2022),
    (b"c", 0x0063),
    (b"caron", 0x02C7),
    (b"ccedilla", 0x00E7),
    (b"cedilla", 0x00B8),
    (b"cent", 0x00A2),
    (b"chi", 0x03C7),
    (b"circumflex", 0x02C6),
    (b"colon", 0x003A),
    (b"comma", 0x002C),
    (b"copyright", 0x00A9),
    (b"currency", 0x00A4),
    (b"d", 0x0064),
    (b"dagger", 0x2020),
    (b"daggerdbl", 0x2021),
    (b"degree", 0x00B0),
    (b"delta", 0x03B4),
    (b"dieresis", 0x00A8),
    (b"divide", 0x00F7),
    (b"dollar", 0x0024),
    (b"dotaccent", 0x02D9),
    (b"dotlessi", 0x0131),
    (b"dotlessj", 0x0237),
    (b"e", 0x0065),
    (b"eacute", 0x00E9),
    (b"ecircumflex", 0x00EA),
    (b"edieresis", 0x00EB),
    (b"egrave", 0x00E8),
    (b"eight", 0x0038),
    (b"ellipsis", 0x2026),
    (b"emdash", 0x2014),
    (b"endash", 0x2013),
    (b"epsilon", 0x03B5),
    (b"equal", 0x003D),
    (b"eta", 0x03B7),
    (b"eth", 0x00F0),
    (b"exclam", 0x0021),
    (b"exclamdown", 0x00A1),
    (b"f", 0x0066),
    (b"ff", 0xFB00),
    (b"ffi", 0xFB03),
    (b"ffl", 0xFB04),
    (b"fi", 0xFB01),
    (b"five", 0x0035),
    (b"fl", 0xFB02),
    (b"florin", 0x0192),
    (b"four", 0x0034),
    (b"fraction", 0x2044),
    (b"g", 0x0067),
    (b"gamma", 0x03B3),
    (b"germandbls", 0x00DF),
    (b"grave", 0x0060),
    (b"greater", 0x003E),
    (b"greaterequal", 0x2265),
    (b"guillemotleft", 0x00AB),
    (b"guillemotright", 0x00BB),
    (b"guilsinglleft", 0x2039),
    (b"guilsinglright", 0x203A),
    (b"h", 0x0068),
    (b"hungarumlaut", 0x02DD),
    (b"hyphen", 0x002D),
    (b"i", 0x0069),
    (b"iacute", 0x00ED),
    (b"icircumflex", 0x00EE),
    (b"idieresis", 0x00EF),
    (b"igrave", 0x00EC),
    (b"infinity", 0x221E),
    (b"integral", 0x222B),
    (b"iota", 0x03B9),
    (b"j", 0x006A),
    (b"k", 0x006B),
    (b"kappa", 0x03BA),
    (b"l", 0x006C),
    (b"lambda", 0x03BB),
    (b"less", 0x003C),
    (b"lessequal", 0x2264),
    (b"logicalnot", 0x00AC),
    (b"lozenge", 0x25CA),
    (b"lslash", 0x0142),
    (b"m", 0x006D),
    (b"macron", 0x00AF),
    (b"minus", 0x2212),
    (b"mu", 0x00B5),
    (b"multiply", 0x00D7),
    (b"n", 0x006E),
    (b"nbspace", 0x00A0),
    (b"nine", 0x0039),
    (b"notequal", 0x2260),
    (b"ntilde", 0x00F1),
    (b"nu", 0x03BD),
    (b"numbersign", 0x0023),
    (b"o", 0x006F),
    (b"oacute", 0x00F3),
    (b"ocircumflex", 0x00F4),
    (b"odieresis", 0x00F6),
    (b"oe", 0x0153),
    (b"ogonek", 0x02DB),
    (b"ograve", 0x00F2),
    (b"omega", 0x03C9),
    (b"omicron", 0x03BF),
    (b"one", 0x0031),
    (b"onehalf", 0x00BD),
    (b"onequarter", 0x00BC),
    (b"onesuperior", 0x00B9),
    (b"ordfeminine", 0x00AA),
    (b"ordmasculine", 0x00BA),
    (b"oslash", 0x00F8),
    (b"otilde", 0x00F5),
    (b"p", 0x0070),
    (b"paragraph", 0x00B6),
    (b"parenleft", 0x0028),
    (b"parenright", 0x0029),
    (b"partialdiff", 0x2202),
    (b"percent", 0x0025),
    (b"period", 0x002E),
    (b"periodcentered", 0x00B7),
    (b"perthousand", 0x2030),
    (b"phi", 0x03C6),
    (b"pi", 0x03C0),
    (b"plus", 0x002B),
    (b"plusminus", 0x00B1),
    (b"product", 0x220F),
    (b"psi", 0x03C8),
    (b"q", 0x0071),
    (b"question", 0x003F),
    (b"questiondown", 0x00BF),
    (b"quotedbl", 0x0022),
    (b"quotedblbase", 0x201E),
    (b"quotedblleft", 0x201C),
    (b"quotedblright", 0x201D),
    (b"quoteleft", 0x2018),
    (b"quoteright", 0x2019),
    (b"quotesinglbase", 0x201A),
    (b"quotesingle", 0x0027),
    (b"r", 0x0072),
    (b"radical", 0x221A),
    (b"registered", 0x00AE),
    (b"rho", 0x03C1),
    (b"ring", 0x02DA),
    (b"s", 0x0073),
    (b"scaron", 0x0161),
    (b"section", 0x00A7),
    (b"semicolon", 0x003B),
    (b"seven", 0x0037),
    (b"sfthyphen", 0x00AD),
    (b"sigma", 0x03C3),
    (b"six", 0x0036),
    (b"slash", 0x002F),
    (b"space", 0x0020),
    (b"sterling", 0x00A3),
    (b"summation", 0x2211),
    (b"t", 0x0074),
    (b"tau", 0x03C4),
    (b"theta", 0x03B8),
    (b"thorn", 0x00FE),
    (b"three", 0x0033),
    (b"threequarters", 0x00BE),
    (b"threesuperior", 0x00B3),
    (b"tilde", 0x02DC),
    (b"trademark", 0x2122),
    (b"two", 0x0032),
    (b"twosuperior", 0x00B2),
    (b"u", 0x0075),
    (b"uacute", 0x00FA),
    (b"ucircumflex", 0x00FB),
    (b"udieresis", 0x00FC),
    (b"ugrave", 0x00F9),
    (b"underscore", 0x005F),
    (b"upsilon", 0x03C5),
    (b"v", 0x0076),
    (b"w", 0x0077),
    (b"x", 0x0078),
    (b"xi", 0x03BE),
    (b"y", 0x0079),
    (b"yacute", 0x00FD),
    (b"ydieresis", 0x00FF),
    (b"yen", 0x00A5),
    (b"z", 0x007A),
    (b"zcaron", 0x017E),
    (b"zero", 0x0030),
    (b"zeta", 0x03B6),
];

/// Unicode for a glyph name: the table, then `uniXXXX`, `uXXXX[XX]`.
pub fn glyph_to_unicode(name: &[u8]) -> Option<char> {
    if let Ok(i) = NAME_TO_UNICODE.binary_search_by(|(n, _)| (*n).cmp(name)) {
        return char::from_u32(NAME_TO_UNICODE[i].1);
    }
    // `a.sc`, `f_i.alt`: drop the suffix.
    if let Some(dot) = name.iter().position(|&b| b == b'.') {
        if dot > 0 {
            return glyph_to_unicode(&name[..dot]);
        }
    }
    let hex = |s: &[u8]| -> Option<u32> {
        let s = core::str::from_utf8(s).ok()?;
        u32::from_str_radix(s, 16).ok()
    };
    if let Some(rest) = name.strip_prefix(b"uni") {
        if rest.len() >= 4 {
            return char::from_u32(hex(&rest[..4])?);
        }
    }
    if let Some(rest) = name.strip_prefix(b"u") {
        if (4..=6).contains(&rest.len()) {
            return char::from_u32(hex(rest)?);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_agree_with_their_codecs() {
        assert_eq!(WIN_ANSI[0x80], Some(&b"Euro"[..]));
        assert_eq!(STANDARD[0x27], Some(&b"quoteright"[..]));
        assert_eq!(MAC_ROMAN[0x8E], Some(&b"eacute"[..]));
        assert_eq!(glyph_to_unicode(b"eacute"), Some('\u{e9}'));
        assert_eq!(glyph_to_unicode(b"uni20AC"), Some('\u{20ac}'));
        assert_eq!(glyph_to_unicode(b"A.sc"), Some('A'));
    }
}
